action_index = {
    "verbs": {
        "attack": "attack",
        "check": "look",
        "equip": "equip",
        "examine": "look",
        "exit": "quit",
        "help": "help",
        "inspect": "look",
        "investigate": "look",
        "look": "look",
        "move": "move",
        "quit": "quit",
        "read": "read",
        "show": "look",
        "travel": "travel",
        "use": "use",
        "view": "look",
    },
    "nouns": [
        "character",
        "east",
        "equipment",
        "inventory",
        "journal",
        "map",
        "monster",
        "north",
        "room",
        "south",
        "stats",
        "west",
        "world",
        "zone",
    ]
}